package:
    type:           library
    name:           omnipay-yandexmoney
    namespace:      Omnipay\YandexMoney
    headline:       'Omnipay: Yandex.Money'
    title:          Yandex.Money driver for Omnipay PHP payment library
    license:        MIT
    keywords:       php, omnipay, yandex.money, merchant, payment
    year:           2017
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [Yandex.Money](https://money.yandex.ru/) support for Omnipay.

