package:
    name:           omnipay-yandexmoney
    namespace:      hiqdev\php\merchant\yandexmoney
    headline:       Omnipay: Yandex.Money
    title:          Yandex.Money driver for Omnipay PHP payment library
    type:           library
    license:        MIT
    keywords:       php, omnipay, yandex.money, merchant, payment
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.
        This package implements [Yandex.Money](https://money.yandex.ru/) support for Omnipay.

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
